apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: host-data
      hostPath:
        path: /home/labex/project/k8s-volume-demo/data
        type: Directory