apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: secure-ops
  name: cluster-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secure-ops
  name: resource-reader
rules:
  - apiGroups: [""]
    resources: ["deployments", "pods", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "patch"]
