apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: audit-zone
spec:
  securityContext:
    fsGroup: 2000
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: host-data
          mountPath: /data

  volumes:
    - name: host-data
      hostPath:
        path: /home/labex/project/k8s-volume-demo/data
        type: Directory